### ISSUE TITLE
Error ENOENT

### ISSUE THREAD

**Issue by peterennisrda** [ionic-team/component-preview#1]
Windows 10

```
C:\ae\component-preview>npm -v
6.1.0

C:\ae\component-preview>npm list @stencil/core
component-preview@0.1.0 C:\ae\component-preview
`-- @stencil/core@0.9.11
```

![capture062](https://user-images.githubusercontent.com/1280523/42106114-b696322a-7b87-11e8-9b75-56368b1836e2.png)
![capture063](https://user-images.githubusercontent.com/1280523/42106121-bce5c8a2-7b87-11e8-8750-1970f3ebccbb.png)

**Comment by camwiegert** [comment]
Closing this under the assumption that it was addressed by upgrading Stencil. Please reopen in the [docs repo](https://github.com/ionic-team/ionic-docs/issues) if that isn't the case. Thank you!
