### ISSUE TITLE
Fab layout problem

### ISSUE THREAD

**Issue by peterennis** [ionic-team/component-preview#2]
```
C:\ae\aedev\component-preview>ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.0.1

System:

   NodeJS : v8.11.1
   npm    : 6.2.0
   OS     : Windows 10


C:\ae\aedev\component-preview>
```

![capture352](https://user-images.githubusercontent.com/140737/43242203-81472642-9054-11e8-90d7-19447ef084cc.png)

https://github.com/ionic-team/component-preview/tree/master/src/components/fab

**Comment by camwiegert** [comment]
@peterennis Thanks for opening this! I'm going to close as it is [duplicated in the docs repo](https://github.com/ionic-team/ionic-docs/issues/48).  We're going to close this issue board and request that issues be opened there.
