### ISSUE TITLE
Virtual scroll alignment

### ISSUE THREAD

**Issue by peterennis** [ionic-team/component-preview#4]
The top scroll bar disappears behind the header.
Does not align at zero.
Bottom stops correctly at 499.
![virtual-scroll](https://user-images.githubusercontent.com/140737/43243313-f6502226-905a-11e8-9954-fdc32c9ec870.gif)

**Comment by camwiegert** [comment]
@peterennis  I'm unable to reproduce this. If you would, please reopen with steps to reproduce in the [docs repo](https://github.com/ionic-team/ionic-docs/issues).
