### ISSUE TITLE
Refresher is stale

### ISSUE THREAD

**Issue by peterennis** [ionic-team/component-preview#5]
Code indicates it should refresh new values?
![refresher](https://user-images.githubusercontent.com/140737/43243481-d1dd6f38-905b-11e8-9ba0-e7fed9b0482e.gif)
![capture353](https://user-images.githubusercontent.com/140737/43243552-1104dae8-905c-11e8-8282-d7220398aacc.png)

**Comment by camwiegert** [comment]
@peterennis The refresher demo is triggered by pull-to-refresh, not a page refresh:

![refresher](https://user-images.githubusercontent.com/2547860/43274354-9b945cb6-90c4-11e8-9188-045cc22de273.gif)
